name: 每天自动推送3D试机号

on:
  schedule:
    # 国际标准时间(UTC) 10:35 对应 北京时间 18:35 (UTC+8)
    - cron: '11 11 * * *'
  # 支持在 GitHub 网页上点按钮手动立即测试一次
  workflow_dispatch:

jobs:
  run-spider:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 运行环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 运行抓取并推送
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
        run: |
          python push_3d.py
